cp -r ../../../../vendor/oplus/kernel/oplus_performance/task_cpustats/ ./fs/proc/task_cpustats
cp -r ../../../../vendor/oplus/kernel/oplus_performance/gloom_new/va_feature_node.h ./fs/proc/va_feature_node.h
cp -r ../../../../vendor/oplus/kernel/oplus_performance/healthinfo/fs ./fs/proc/healthinfo
cp -r ../../../../../vendor/oplus/kernel/secureguard/securegki/ ./arch/arm64/kernel/secureguard
cp -r ../../../vendor/oplus/kernel/network ./net/oplus_modules
cp -r ../../../../vendor/oplus/secure/biometrics/fingerprints/bsp/uff/driver/ ./drivers/input/uff_fp_drivers
cp -r ../../../../../vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2/ ./drivers/input/touchscreen/oplus_touchscreen_v2
cp -r ../../../../../vendor/oplus/secure/biometrics/fingerprints/bsp/drivers/anc_capacitive_driver ./drivers/input/oplus_fp_drivers/anc_capacitive_driver
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/memleak_detect/svelte ./drivers/soc/oplus/svelte
cp -r ../../../../../vendor/oplus/sensor/kernel/qcom/sensor/ ./drivers/soc/oplus/sensor
cp -r ../../../../../vendor/oplus/kernel/power/midas ./drivers/soc/oplus/midas
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/lowmem_dbg ./drivers/soc/oplus/lowmem_dbg
cp -r ../../../../../vendor/oplus/kernel/system/ ./drivers/soc/oplus/system
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/oplus_nandswap ./drivers/soc/oplus/oplus_nandswap
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/healthinfo/main/ ./drivers/soc/oplus/healthinfo
cp -r ../../../../../vendor/oplus/kernel/explorer/ ./drivers/soc/oplus/explorer
cp -r ../../../../../vendor/oplus/kernel/wakelock_profiler ./drivers/soc/oplus/oplus_wakelock
cp -r ../../../../../vendor/oplus/kernel/thermal/ ./drivers/soc/oplus/thermal
cp -r ../../../../../vendor/oplus/kernel/device_info/device_info/ ./drivers/soc/oplus/device_info
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/im ./drivers/soc/oplus/im
cp -r ../../../../../vendor/oplus/kernel/misc/ ./drivers/soc/oplus/misc
cp -r ../../../../../vendor/oplus/sensor/kernel/oplus_consumer_ir ./drivers/soc/oplus/oplus_consumer_ir
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/cpufreq_bouncing/ ./drivers/soc/oplus/cpufreq_bouncing
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/tpd/ ./drivers/soc/oplus/tpd
cp -r ../../../../vendor/oplus/kernel/misc/oplus_rf_cable_monitor.c ./drivers/misc/oplus_rf_cable_monitor.c
cp -r ../../../../vendor/oplus/kernel/misc/sim_detect.c ./drivers/misc/sim_detect.c
cp -r ../../../../vendor/oplus/kernel/vibrator/aw8697_haptic ./drivers/misc/aw8697_haptic
cp -r ../../../../vendor/oplus/kernel/touchpanel/kernelFwUpdate ./drivers/base/kernelFwUpdate
cp -r ../../../../vendor/oplus/kernel/charger/ ./drivers/power/oplus
cp -r ../../../../../../vendor/oplus/kernel/oplus_performance/healthinfo/ion ./drivers/staging/android/ion/oplus_ion
cp -r ../../../vendor/oplus/kernel/oplus_performance/sched_assist ./kernel/sched_assist
cp -r ../../../vendor/oplus/kernel/oplus_performance/special_opt ./kernel/special_opt
cp -r ../../../vendor/oplus/kernel/oplus_performance/memleak_detect/stack_depot/memleak_debug_stackdepot.c ./lib/memleak_debug_stackdepot.c
cp -r ../../../../../vendor/oplus/kernel/device_info/device_info/device_info.h ./include/soc/oplus/device_info.h
cp -r ../../../../../vendor/oplus/kernel/system/include ./include/soc/oplus/system
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/healthinfo/main/healthinfo.h ./include/soc/oplus/healthinfo.h
cp -r ../../../../../vendor/oplus/kernel/system/include/boot_mode.h ./include/soc/oplus/boot_mode.h
cp -r ../../../../../vendor/oplus/kernel/oplus_performance/lowmem_dbg/lowmem_dbg.h ./include/soc/oplus/lowmem_dbg.h
cp -r ../../../../vendor/oplus/kernel/oplus_performance/task_cpustats/task_sched_info.h ./include/linux/task_sched_info.h
cp -r ../../../../vendor/oplus/kernel/oplus_performance/cpufreq_bouncing ./include/linux/cpufreq_bouncing
cp -r ../../../../vendor/oplus/kernel/oplus_performance/healthinfo/include ./include/linux/healthinfo
cp -r ../../../../vendor/oplus/kernel/oplus_performance/im ./include/linux/im
cp -r ../../../../vendor/oplus/kernel/oplus_performance/memleak_detect/stack_depot/memleak_stackdepot.h ./include/linux/memleak_stackdepot.h
cp -r ../../../../vendor/oplus/kernel/oplus_performance/gloom_new/reserve_area.h ./include/linux/reserve_area.h
cp -r ../../../../vendor/oplus/kernel/oplus_performance/tpd ./include/linux/tpd
cp -r ../../../../vendor/oplus/kernel/oplus_performance/task_cpustats/task_cpustats.h ./include/linux/task_cpustats.h
cp -r ../../../../vendor/oplus/kernel/oplus_performance/process_reclaim/process_mm_reclaim.h ./include/linux/process_mm_reclaim.h
cp -r ../../../../vendor/oplus/kernel/oplus_performance/sched_assist ./include/linux/sched_assist
cp -r ../../../vendor/oplus/kernel/oplus_performance/multi_freearea/multi_freearea.c ./mm/multi_freearea.c
cp -r ../../../vendor/oplus/kernel/oplus_performance/gloom_new/arch_mmap.h ./mm/arch_mmap.h
cp -r ../../../vendor/oplus/kernel/oplus_performance/gloom_new/reserve_area.c ./mm/reserve_area.c
cp -r ../../../vendor/oplus/kernel/oplus_performance/healthinfo/mm ./mm/healthinfo
cp -r ../../../vendor/oplus/kernel/oplus_performance/mm_osvelte/ ./mm/mm_osvelte
cp -r ../../../vendor/oplus/kernel/oplus_performance/oplus_mm/zram_opt ./mm/zram_opt
cp -r ../../../vendor/oplus/kernel/oplus_performance/multi_freearea/multi_freearea.h ./mm/multi_freearea.h
cp -r ../../../vendor/oplus/kernel/oplus_performance/oplus_mm/process_reclaim ./mm/process_reclaim
cp -r ../../../vendor/oplus/kernel/oplus_performance/memleak_detect/task_mem ./mm/task_mem
cp -r ../../../vendor/oplus/kernel/oplus_performance/memleak_detect/malloc_track ./mm/malloc_track
